### ISSUE TITLE
상속, 인터페이스 문제 푸시 전 확인차 질문

### ISSUE THREAD

**Issue by kysan1014** [kysan1014/increpas2020_group#13]
음.. 주말동안 상속, 인터페이스 문제를 만들기는 했는데, 스윙을 사용하는 문제로 만들어버렸네요. 만들고나서 조금 잘못했나라는 생각을 했습니다만, 아깝더라고요.

그래서 확인차 여쭤봅니다. 두 가지 옵션이 있는데, 1) 모든 클래스, 인터페이스 전부 푸시하고 가장 필요한 기능 구현만을 요구하기, 2) 최소한의 클래스와 인터페이스 구조만을 푸시하고 거의 대부분을 본인 스타일대로 코딩해보기, 이 두 가지가 있습니다. 

몇몇 분들은 어렵게 느끼실 수 있을테고, 몇몇 분들은 실제로 조금만 생각하시면 푸실 수 있는 분들도 계십니다. 코멘트로던 개인 톡으로던 저에게 어떤 것이 좋은지 알려주시면 감사하겠습니다. 

1번으로 푸시하게 될 경우, 푸실 수 있는 분들도 뭔가 제 코드대로 생각하게 될 것 같습니다. 다양한 코드를 보는 것이 좋다고 생각이 듭니다. 두 가지 옵션에 대한 요청이 전부 들어오면, 만들어는 보겠습니다. 현재는 제 소스코드만 있습니다.

**Comment by jovensol1993** [comment]
저는 1번이요 . 제실력에 처음부터 2하면 너무 어려울것같아서요
