### ISSUE TITLE
주간 할 일

### ISSUE THREAD

**Issue by kysan1014** [kysan1014/increpas2020_group#5]
한 주에 할 일:
   
   1. __일인 당 매주 하나 이상의 이슈를 던짐 (요일 무관)__
      - 이슈는 연습 문제에 대한 요청, 연습 문제 배포, 질문 등을 포함
         - 연습 문제에 대한 요청을 이슈로 작성하였을 경우, 이슈 작성자는 의무적으로 작성한 소스 코드를 푸시
         - 연습 문제 배포를 이슈로 작성하였을 경우, 이슈 작성자는 자세히 (또는 친절히) 주석을 남길 것을 권고
         -  질문을 이슈로 작성하였을 경우, 이슈 작성자는 다른 사람이 코멘트로 남긴 내용을 바탕으로 소스 코드를 작성하거나, 그 외에 추가적으로 공부한 내용을 txt, java, sql 등의 파일로 작성하여 배포
      - 이슈 작성 시 참고한 문헌이나 사이트가 있다면, 반드시 출처를 표시함    
   
   2. __일인 당 매주 하나 이상의 이슈에 코멘트를 작성 (요일 무관)__
      - 코멘트를 작성할 때, 참고한 내용이 있으면 그 출처를 분명히 밝힘
      - 연습 문제에 대한 요청으로 이슈를 작성하였을 경우, 요청한 이슈에 코멘트로 알림    
   
이 두 가지는 한 주에 일요일 하루, 3~4 시간 정도의 시간만을 투자한다고 가정하였을 때에도 할 수 있을 것으로 생각되는 내용입니다. 추가적인 제안이나 수정사항 받습니다. 자유롭게 의견을 남겨주세요.

**Comment by kysan1014** [comment]
다만, 돌아오는 주의 경우는 조금 달라지기 때문에, 이에 대한 제안도 받습니다.

**Comment by ckdn9595** [comment]
돌아오는 주의 의견은 따로 없고,
올려주신 내용은 모두 동의하고 이견없습니다.
